services:
   
  catalogdb:
   container_name: catalogdb
   restart: always
   ports:
   - "27019:27017"
   volumes:
   - mongodb_data:/data/db
   
  basketdb:
   container_name: basketdb
   restart: always
   ports:
   - "6379:6379"

  catalog.api:
     environment:
      - ASPNETCORE_ENVIRONMENT=Development
     depends_on:
      - catalogdb
     ports:
      - "8000:80"


  basket.api:
    container_name: basket.Api 
    depends_on:
    - basketdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8001:80"

