services:
  catalogdb:
   image: mongo
  
  basketdb:
   image: redis

  discountdb:
   image: postgres

  pgadmin:
   image: dpage/pgadmin4

  orderdb:
   image: mcr.microsoft.com/mssql/server
   
  rabbitmq:
    image: rabbitmq

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: Services/Catalog/Catalog.Api
      dockerfile: Dockerfile
  
  portainer:
   image: portainer/portainer-ce

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.Api/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

 

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.Api/Dockerfile

volumes:
  mongodb_data:
  portainer_data:
  postgres_data:
  pgadmin_data:  
  sqlserver_data:


